# Task #09 指定教材：資料探勘與關聯分析
Practice

In [2]:
import pandas as pd

data = {
    '顧客 ID': ['A', 'A', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'D', 'D', 'D', 'D', 'E', 'E', 'E', 'F', 'F', 'G', 'G'],
    '商品名稱': ['可樂', '洋芋片', '啤酒', '花生', '餅乾', '可樂', '洋芋片', '花生', '餅乾', '可樂', '啤酒', '花生', '餅乾', '可樂', '啤酒', '餅乾', '可樂', '花生', '啤酒', '餅乾'],
    '購買日期': ['2022/01/01', '2022/01/01', '2022/01/02', '2022/01/02', '2022/01/02', '2022/01/03', '2022/01/03', '2022/01/03', '2022/01/03', '2022/01/04', '2022/01/04', '2022/01/04', '2022/01/04', '2022/01/05', '2022/01/05', '2022/01/05', '2022/01/06', '2022/01/06', '2022/01/07', '2022/01/07']
}

df = pd.DataFrame(data)
df

   顧客 ID 商品名稱        購買日期
0      A   可樂  2022/01/01
1      A  洋芋片  2022/01/01
2      B   啤酒  2022/01/02
3      B   花生  2022/01/02
4      B   餅乾  2022/01/02
5      C   可樂  2022/01/03
6      C  洋芋片  2022/01/03
7      C   花生  2022/01/03
8      C   餅乾  2022/01/03
9      D   可樂  2022/01/04
10     D   啤酒  2022/01/04
11     D   花生  2022/01/04
12     D   餅乾  2022/01/04
13     E   可樂  2022/01/05
14     E   啤酒  2022/01/05
15     E   餅乾  2022/01/05
16     F   可樂  2022/01/06
17     F   花生  2022/01/06
18     G   啤酒  2022/01/07
19     G   餅乾  2022/01/07

In [5]:
# 將資料集按照顧客 ID 及商品名稱進行分組
grouped = df.groupby(['顧客 ID', '商品名稱'])['購買日期'].count().reset_index()
grouped

   顧客 ID 商品名稱  購買日期
0      A   可樂     1
1      A  洋芋片     1
2      B   啤酒     1
3      B   花生     1
4      B   餅乾     1
5      C   可樂     1
6      C  洋芋片     1
7      C   花生     1
8      C   餅乾     1
9      D   可樂     1
10     D   啤酒     1
11     D   花生     1
12     D   餅乾     1
13     E   可樂     1
14     E   啤酒     1
15     E   餅乾     1
16     F   可樂     1
17     F   花生     1
18     G   啤酒     1
19     G   餅乾     1

In [8]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

# 將資料集轉換成 one-hot 編碼
hot_encoded = grouped.pivot(index='顧客 ID', columns='商品名稱', values='購買日期').fillna(0)

# 進行 Apriori 演算法分析
frequent_itemsets = apriori(hot_encoded, min_support=0.2, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.5)

# 按照信賴度排序並輸出結果
rules.sort_values('confidence', ascending=False, inplace=True)
print(rules[['antecedents', 'consequents', 'support', 'confidence']])

   antecedents consequents   support  confidence
13    (啤酒, 可樂)        (餅乾)  0.285714    1.000000
1        (洋芋片)        (可樂)  0.285714    1.000000
8         (啤酒)        (餅乾)  0.571429    1.000000
20    (啤酒, 花生)        (餅乾)  0.285714    1.000000
9         (餅乾)        (啤酒)  0.571429    0.800000
10        (花生)        (餅乾)  0.428571    0.750000
2         (花生)        (可樂)  0.428571    0.750000
17    (花生, 可樂)        (餅乾)  0.285714    0.666667
16    (花生, 餅乾)        (可樂)  0.285714    0.666667
14    (餅乾, 可樂)        (啤酒)  0.285714    0.666667
18    (餅乾, 可樂)        (花生)  0.285714    0.666667
22    (花生, 餅乾)        (啤酒)  0.285714    0.666667
11        (餅乾)        (花生)  0.428571    0.600000
5         (可樂)        (餅乾)  0.428571    0.600000
4         (餅乾)        (可樂)  0.428571    0.600000
3         (可樂)        (花生)  0.428571    0.600000
23        (啤酒)    (花生, 餅乾)  0.285714    0.500000
21    (啤酒, 餅乾)        (花生)  0.285714    0.500000
0         (啤酒)        (可樂)  0.285714    0.500000
12    (啤酒, 餅乾)        (可樂)  0.285714    0.500000
19        (花生)    (餅乾, 可樂)  0.285714    0.500000
15        (啤酒)    (餅乾, 可樂)  0.285714    0.500000
7         (花生)        (啤酒)  0.285714    0.500000
6         (啤酒)        (花生)  0.285714    0.500000
24        (花生)    (啤酒, 餅乾)  0.285714    0.500000

/opt/anaconda3/lib/python3.8/site-packages/mlxtend/frequent_patterns/fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [9]:
hot_encoded

商品名稱    可樂   啤酒  洋芋片   花生   餅乾
顧客 ID
A      1.0  0.0  1.0  0.0  0.0
B      0.0  1.0  0.0  1.0  1.0
C      1.0  0.0  1.0  1.0  1.0
D      1.0  1.0  0.0  1.0  1.0
E      1.0  1.0  0.0  0.0  1.0
F      1.0  0.0  0.0  1.0  0.0
G      0.0  1.0  0.0  0.0  1.0

In [10]:
frequent_itemsets

     support      itemsets
0   0.714286          (可樂)
1   0.571429          (啤酒)
2   0.285714         (洋芋片)
3   0.571429          (花生)
4   0.714286          (餅乾)
5   0.285714      (啤酒, 可樂)
6   0.285714     (可樂, 洋芋片)
7   0.428571      (花生, 可樂)
8   0.428571      (餅乾, 可樂)
9   0.285714      (啤酒, 花生)
10  0.571429      (啤酒, 餅乾)
11  0.428571      (花生, 餅乾)
12  0.285714  (啤酒, 餅乾, 可樂)
13  0.285714  (花生, 餅乾, 可樂)
14  0.285714  (啤酒, 花生, 餅乾)

In [11]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
13,"(啤酒, 可樂)",(餅乾),0.285714,0.714286,0.285714,1.000000,1.400000,0.081633,inf,0.400000
1,(洋芋片),(可樂),0.285714,0.714286,0.285714,1.000000,1.400000,0.081633,inf,0.400000
8,(啤酒),(餅乾),0.571429,0.714286,0.571429,1.000000,1.400000,0.163265,inf,0.666667
20,"(啤酒, 花生)",(餅乾),0.285714,0.714286,0.285714,1.000000,1.400000,0.081633,inf,0.400000
9,(餅乾),(啤酒),0.714286,0.571429,0.571429,0.800000,1.400000,0.163265,2.142857,1.000000
10,(花生),(餅乾),0.571429,0.714286,0.428571,0.750000,1.050000,0.020408,1.142857,0.111111
2,(花生),(可樂),0.571429,0.714286,0.428571,0.750000,1.050000,0.020408,1.142857,0.111111
17,"(花生, 可樂)",(餅乾),0.428571,0.714286,0.285714,0.666667,0.933333,-0.020408,0.857143,-0.111111
16,"(花生, 餅乾)",(可樂),0.428571,0.714286,0.285714,0.666667,0.933333,-0.020408,0.857143,-0.111111
14,"(餅乾, 可樂)",(啤酒),0.428571,0.571429,0.285714,0.666667,1.166667,0.040816,1.285714,0.250000
18,"(餅乾, 可樂)",(花生),0.428571,0.571429,0.285714,0.666667,1.166667,0.040816,1.285714,0.250000
22,"(花生, 餅乾)",(啤酒),0.428571,0.571429,0.285714,0.666667,1.166667,0.040816,1.285714,0.250000
11,(餅乾),(花生),0.714286,0.571429,0.428571,0.600000,1.050000,0.020408,1.071429,0.166667
5,(可樂),(餅乾),0.714286,0.714286,0.428571,0.600000,0.840000,-0.081633,0.714286,-0.400000
4,(餅乾),(可樂),0.714286,0.714286,0.428571,0.600000,0.840000,-0.081633,0.714286,-0.400000
3,(可樂),(花生),0.714286,0.571429,0.428571,0.600000,1.050000,0.020408,1.071429,0.166667
23,(啤酒),"(花生, 餅乾)",0.571429,0.428571,0.285714,0.500000,1.166667,0.040816,1.142857,0.333333
21,"(啤酒, 餅乾)",(花生),0.571429,0.571429,0.285714,0.500000,0.875000,-0.040816,0.857143,-0.250000
0,(啤酒),(可樂),0.571429,0.714286,0.285714,0.500000,0.700000,-0.122449,0.571429,-0.500000
12,"(啤酒, 餅乾)",(可樂),0.571429,0.714286,0.285714,0.500000,0.700000,-0.122449,0.571429,-0.500000
19,(花生),"(餅乾, 可樂)",0.571429,0.428571,0.285714,0.500000,1.166667,0.040816,1.142857,0.333333
15,(啤酒),"(餅乾, 可樂)",0.571429,0.428571,0.285714,0.500000,1.166667,0.040816,1.142857,0.333333
7,(花生),(啤酒),0.571429,0.571429,0.285714,0.500000,0.875000,-0.040816,0.857143,-0.250000
6,(啤酒),(花生),0.571429,0.571429,0.285714,0.500000,0.875000,-0.040816,0.857143,-0.250000
24,(花生),"(啤酒, 餅乾)",0.571429,0.571429,0.285714,0.500000,0.875000,-0.040816,0.857143,-0.250000